DF.Web/Controllers/ScriptsController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace DF.Web.Controllers
{
    public class ScriptsController : Controller
    {
        // GET: Scripts
        [AllowAnonymous]
        public ActionResult Constants()
        {
            // Obviously this will be dynamically generated
            var script = new StringBuilder();
            script.Append("(function () {");
            script.Append("angular.module('app')");
            script.Append(".constant('Settings', {");
            script.AppendFormat("ApiUrl: '{0}',", ConfigurationManager.AppSettings["ApiUrl"]);
            script.Append("});");
            script.Append("})();");
            return JavaScript(script.ToString());
        }
    }
}

DF.Web/Views/Shared/_DealFooter.cshtml
<div>
    @*<div class="btn-group" role="group">
        <button type="button" class="btn btn-default"><i class="fa fa-eye"></i>&nbsp;12 Viewed</button>
        <button type="button" class="btn btn-default"><i class="fa fa-heart pink"></i>&nbsp;24</button>
        <button type="button" class="btn btn-default"><i class="fa fa-star orange"></i>&nbsp;Add To Favorite</button>
        <button type="button" class="btn btn-default"><i class="btr bt-forward"></i>&nbsp;Share</button>
    </div>*@
    <span class='st_sharethis' displaytext='ShareThis'></span>
    <span class='st_facebook' displaytext='Facebook'></span>
    <span class='st_twitter' displaytext='Tweet'></span>
    <span class='st_linkedin' displaytext='LinkedIn'></span>
    <span class='st_pinterest' displaytext='Pinterest'></span>
    <span class='st_email' displaytext='Email'></span>
</div>

DF.Web/Views/Shared/_Footer.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h4>Deals</h4>
                <ul>
                    <li><a href="/#/category/top">Top Deals</a></li>
                    <li><a href="/#/category/dining">Dining</a></li>
                    <li><a href="/#/category/happy-hour">Happy Hour</a></li>
                    <li><a href="/#/category/accomodation">Accomodation</a></li>
                    <li><a href="/#/category/Health-beauty">Health & Beauty</a></li>
                    <li><a href="/#/category/travel">Travel & Leisure</a></li>
                    <li><a href="/#/category/fashion">Fashion</a></li>
                    <li><a href="/#/category/home-essentials">Home Essentials</a></li>
                    <li><a href="/#/category/electronics">Electronics</a></li>
                    <li><a href="/#/category/other">Other</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                <h4>Partners</h4>
                <ul>
                    <li><a href="/#/partners/hsbc">HSBC</a></li>
                    <li><a href="/#/partners/amex">AMEX - American Express</a></li>
                    <li><a href="/#/partners/commercial-bank">Commercial Bank</a></li>
                    <li><a href="/#/partners/sampath-bank">Sampath Bank</a></li>
                    <li><a href="/#/partners/hnb">HNB</a></li>
                    <li><a href="/#/partners/standard-charted">Standard Charted</a></li>
                    <li><a href="/#/partners/seylan">Seylan</a></li>
                    <li><a href="/#/partners/visa-card">Visa Card</a></li>
                    <li><a href="/#/partners/master-card">Master Card</a></li>
                    <li><a href="/#/partners/star-points">Star Points</a></li>
                </ul>
            </div>
            <div class="col-md-3">
                
            </div>
            <div class="col-md-3">
                <img src="~/images/logo.png"/>
                <h4>Social</h4>
                <ul>
                    <li><a target="_blank" href="https://www.facebook.com/lankadealfinder">Facebook</a></li>
                </ul>
                <br />
                <h4>Company</h4>
                <ul>
                    <li><a href="/home/about">About</a></li>
                    <li><a href="/home/contact">Contact</a></li>
                    <li><a href="/home/disclaimer">Disclaimer</a></li>
                </ul>
            </div>
        </div>
        @*<div class="privacy hidden-xs">
            <a href="/">Privacy Policy</a>&nbsp;&nbsp;<a href="/">Terms & Conditions</a>
            <div class="pull-right">
                Copyright Redfly 2015
            </div>
        </div>*@
        <br />
        <br/>
        Copyright DealFinder.lk 2016
    </div>
</footer>

DF.Web/Views/Shared/_LandingLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_LandingLayout</title>
</head>
<body>
<div>
    @RenderBody()
</div>
</body>
</html>

DF.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
@using System.Web.UI.WebControls

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/styles")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse hidden-lg hidden-md hidden-sm">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                @Html.Partial("_Nav")
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <nav class="navbar navbar-default hidden-xs">
        <div>
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/#/"><img src="~/images/logo.png" style="padding: 10px" /></a>
</div>
            <div id="navbar" class="navbar-collapse collapse">
                @Html.Partial("_Nav")
            </div><!--/.nav-collapse -->
        </div>
    </nav>
<div class="sub-head">
    <div class="sub-content" style="padding-top: 10px;">
        <a href="/#/"><img src="~/images/logo.png" class="hidden-lg hidden-sm hidden-md" style="position: absolute; top: -30px; left: 0;z-index: 9999999999999999"/></a>
        <h1>One site for all the deals.</h1>
        <div class="hidden-xs">
            @Html.Partial("_Search")
        </div>
        <div class="hidden-lg hidden-md hidden-sm" style="padding: 30px">
            <div class="input-group">
                <input type="text" class="form-control" id="search_text1" style="font-size: 20px; padding: 20px" placeholder="Search for...">
                <span class="input-group-btn">
                    <button class="btn btn-danger btn-search" id="btnSearch1" type="button" onclick="search1()">Search</button>
                </span>
            </div>
        </div>
    </div>

</div>
    <div class="spacer"></div>
<div class="cat-menu hidden-sm hidden-xs">
    <div class="container cat-menu">
        <ul class="nav nav-tabs head-nav">
            <li class="@(@ViewBag.Category == "top" ? "head-tab-active" : "")"><a href="/#/category/top">Top Deals</a></li>
            <li class="@(@ViewBag.Category == "dining" ? "head-tab-active" : "")"><a href="/#/category/dining">Dining</a></li>
            <li class="@(@ViewBag.Category == "happy-hour" ? "head-tab-active" : "")"><a href="/#/category/happy-hour">Happy Hour</a></li>
            <li class="@(@ViewBag.Category == "accomodation" ? "head-tab-active" : "")"><a href="/#/category/accomodation">Accomodation</a></li>
            <li class="@(@ViewBag.Category == "health-beauty" ? "head-tab-active" : "")"><a href="/#/category/health-beauty">Health & Beauty</a></li>
            <li class="@(@ViewBag.Category == "travel-leisure" ? "head-tab-active" : "")"><a href="/#/category/travel-leisure">Travel & Leisure</a></li>
            <li class="@(@ViewBag.Category == "fashion" ? "head-tab-active" : "")"><a href="/category/fashion">Fashion</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More<i class="btr bt-angle-down nav-icon"></i></a>
                <ul class="dropdown-menu">
                    <li><a href="/#/category/home-essentials">Home Essentials</a></li>
                    <li><a href="/#/category/electronics">Electronics</a></li>
                    @*<li><a href="/#/category/other">Other</a></li>*@
                </ul>
            </li>
            
        </ul>
    </div>
</div>
    <div class="container page">
        @RenderBody()
    </div>
    @Html.Partial("_Footer")
    @Scripts.Render("~/scripts/g")
<script>
    function search() {
        if ($('#search_text').val() === '') {
            return;
        }

        window.location = '/home/search?q=' + encodeURIComponent($('#search_text').val());
    }

    function search1() {
        if ($('#search_text1').val() === '') {
            return;
        }

        window.location = '/home/search?q=' + encodeURIComponent($('#search_text1').val());
    }

    $(document).ready(function() {
        $(document).keypress(function(e) {
            if (e.which == 13) {
                $("#btnSearch").click();
            }
        });

        $(document).keypress(function (e) {
            if (e.which == 13) {
                $("#btnSearch1").click();
            }
        });
    });

</script>

    <script type="text/javascript">var switchTo5x = true;</script>
    <script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
    <script type="text/javascript">stLight.options({ publisher: "2fab054b-6cc5-4a49-9806-2e84a0babb25", doNotHash: false, doNotCopy: false, hashAddressBar: false });</script>
</body>
</html>

DF.Web/Views/Shared/_MostViewedDeals.cshtml
@model List<DF.Domain.ActiveDeal>

<div class="most-viewed">

    <h4>Most viewed deals</h4>
    <ul style="list-style-type: none; margin: 0; padding: 0;">
        @foreach (var item in Model)
        {
            @*<li style="margin-bottom: 10px;"><a href="/deals/@Uri.EscapeDataString(item.DealSlug)">@item.Title</a></li>*@

            <li style="margin-bottom: 10px;">
                @if (item.DealSlug != null)
                {
                        <a href="/deals/@Uri.EscapeDataString(item.DealSlug)">@item.Title</a>
                }
                else
                {
                        <a href="">@item.Title</a>
                }
            </li>
        }
    </ul>
</div>

DF.Web/Views/Shared/_Nav.cshtml
@using DF.Web.Controllers
<ul class="nav navbar-nav navbar-right">
    <li><a href="/#/">Home</a></li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Deals<i class="btr bt-angle-down nav-icon"></i></a>
        <ul class="dropdown-menu">
            <li><a href="/#/category/top">Top Deals</a></li>
            <li role="separator" class="divider"></li>
            @*<li class="dropdown-header">Nav header</li>*@
            <li><a href="/#/category/dining">Dining</a></li>
            <li><a href="/#/category/happy-hour">Happy Hour</a></li>
            <li><a href="/#/category/accomodation">Accomodation</a></li>
            <li><a href="/#/category/Health-beauty">Health & Beauty</a></li>
            <li><a href="/#/category/travel-leisure">Travel & Leisure</a></li>
            <li><a href="/#/category/fashion">Fashion</a></li>
            <li><a href="/#/category/home-essentials">Home Essentials</a></li>
            <li><a href="/#/category/electronics">Electronics</a></li>
            @*<li><a href="/#/category/other">Other</a></li>*@
        </ul>
    </li>
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Partners<i class="btr bt-angle-down nav-icon"></i></a>
        <ul class="dropdown-menu">
            <li><a href="/#/partners/hsbc">HSBC</a></li>
            <li><a href="/#/partners/amex">AMEX - American Express</a></li>
            <li><a href="/#/partners/commercial-bank">Commercial Bank</a></li>
            <li><a href="/#/partners/sampath-bank">Sampath Bank</a></li>
            <li><a href="/#/partners/hnb">HNB</a></li>
            <li><a href="/#/partners/standard-charted">Standard Charted</a></li>
            <li><a href="/#/partners/seylan">Seylan</a></li>
            <li><a href="/#/partners/visa-card">Visa Card</a></li>
            <li><a href="/#/partners/master-card">Master Card</a></li>
            <li><a href="/#/partners/star-points">Star Points</a></li>
        </ul>
    </li>
    @if (!User.Identity.IsAuthenticated)
    {
        <li><a href="/#/register">Register</a></li>
        <li><a href="/home/login/">Login</a></li>
    }
    @if (User.Identity.IsAuthenticated)
    {
        <li><a href="/#/profile">@SessionHelper.GetUser()</a></li>
        @*<li><a href="/#/fav"><i class="fa fa-star orange"></i>&nbsp;&nbsp;Favourites</a></li>*@
        <li>@Html.ActionLink("Logout", "Logout", "Home")</li>
    }
</ul>

DF.Web/Views/Shared/_Nothing.cshtml
<div class="panel text-center nothing">
    <i class="fa fa-angellist fa-3 orange" aria-hidden="true"></i>&nbsp;Ooops, No deals here yet.
    <div style="font-size: 18px; margin-top: 5px;">
        <a href="/#/category/top">Try our Top deals!</a>
        
    </div>
</div>

DF.Web/Views/Shared/_Search.cshtml
<script>
    


</script>

<div class="main-search">
    <div class="input-group">
        <input type="text" class="form-control text-search" id="search_text" placeholder="Search for...">
        <span class="input-group-btn">
            <button class="btn btn-danger btn-search" id="btnSearch" type="button" onclick="search()">Search</button>
        </span>
    </div>
</div>

DF.Web/Views/Shared/_SpaLayout.cshtml
@using System.Web.Optimization
@using System.Web.UI.WebControls

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DealFinder.lk - One site for all the deals</title>
    @Styles.Render("~/styles")
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha256-3dkvEK0WLHRJ7/Csr0BZjAWxERc5WH7bdeUya2aXxdU= sha512-+L4yy6FRcDGbXJ9mPG8MT/3UCDzwR9gPeyFNMCtInsol++5m3bk2bXWKdZjvybmohrAsn3Ua5x8gfLnbE1YkOg==" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
</head>
<body ng-app="app" ng-cloak ng-controller="RootController">
    <div style="top:0">
        <nav class="navbar navbar-inverse hidden-lg hidden-md hidden-sm">
            <div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    @Html.Partial("_Nav")
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <nav class="navbar navbar-default hidden-xs">
            <div>
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="/#/"><img src="~/images/logo.png" style="padding: 10px" /></a>
                </div>
                <div id="navbar" class="navbar-collapse collapse">
                    @Html.Partial("_Nav")
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="sub-head">
            <div class="sub-content" style="padding-top: 10px;">
                <a href="/#/"><img src="~/images/logo.png" class="hidden-lg hidden-sm hidden-md" style="position: absolute; top: -30px; left: 0; z-index: 9999999999999999" /></a>
                <h1 class="hidden-sm hidden-xs">One site for all the deals.</h1>
                <div style="font-size: 20px; padding-top: 10px; color: #fff" class="hidden-lg hidden-md">One site for all the deals.</div>
                <div class="hidden-xs">
                    @Html.Partial("_Search")
                </div>
                <div class="hidden-lg hidden-md hidden-sm" style="padding: 30px">
                    <div class="input-group">
                        <input type="text" class="form-control" id="search_text1" style="font-size: 20px; padding: 20px" placeholder="Search for...">
                        <span class="input-group-btn">
                            <button class="btn btn-danger btn-search" id="btnSearch1" type="button" onclick="search1()">Search</button>
                        </span>
                    </div>
                </div>
            </div>

        </div>
        <div class="spacer"></div>
        <div class="cat-menu  hidden-xs hidden-sm">
            <div class="container cat-menu">
                <ul class="nav nav-tabs head-nav">
                    @if (User.Identity.IsAuthenticated)
            {
                        <li><a href="/#/fav"><i class="fa fa-star orange"></i>&nbsp;&nbsp;Favourites</a></li>
            }
                    <li class="@(@ViewBag.Category == "top" ? "head-tab-active" : "")"><a href="/#/category/top">Top Deals</a></li>
                    <li class="@(@ViewBag.Category == "dining" ? "head-tab-active" : "")"><a href="/#/category/dining">Dining</a></li>
                    <li class="@(@ViewBag.Category == "happy-hour" ? "head-tab-active" : "")"><a href="/#/category/happy-hour">Happy Hour</a></li>
                    <li class="@(@ViewBag.Category == "accomodation" ? "head-tab-active" : "")"><a href="/#/category/accomodation">Accomodation</a></li>
                    <li class="@(@ViewBag.Category == "health-beauty" ? "head-tab-active" : "")"><a href="/#/category/health-beauty">Health & Beauty</a></li>
                    <li class="@(@ViewBag.Category == "travel-leisure" ? "head-tab-active" : "")"><a href="/#/category/travel-leisure">Travel & Leisure</a></li>
                    <li class="@(@ViewBag.Category == "fashion" ? "head-tab-active" : "")"><a href="/#/category/fashion">Fashion</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">More<i class="btr bt-angle-down nav-icon"></i></a>
                        <ul class="dropdown-menu">
                            <li><a href="/#/category/home-essentials">Home Essentials</a></li>
                            <li><a href="/#/category/electronics">Electronics</a></li>
                            @*<li><a href="/#/category/other">Other</a></li>*@
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </div>
<div class="container page">
    @RenderBody()
</div>
<div id="load-div" class="load-div">
    <div class="text">
        <i class="fa fa-circle-o-notch fa-spin icon"></i>Loading...
    </div>
</div>
@Html.Partial("_Footer")


@Scripts.Render("~/scripts/g")
@Scripts.Render("~/scripts/app")
<script type="text/javascript" src="@Url.Action("Constants", "Scripts")"></script>
@Scripts.Render("~/scripts/modules")

<script>
    function search() {
        if ($('#search_text').val() === '') {
            return;
        }

        window.location = '/home/search?q=' + encodeURIComponent($('#search_text').val());
    }

    function search1() {
        if ($('#search_text1').val() === '') {
            return;
        }

        window.location = '/home/search?q=' + encodeURIComponent($('#search_text1').val());
    }

    $(document).ready(function() {
        $(document).keypress(function(e) {
            if (e.which == 13) {
                $("#btnSearch").click();
            }
        });

        $(document).keypress(function(e) {
            if (e.which == 13) {
                $("#btnSearch1").click();
            }
        });
    });

</script>
<script>
    (function(i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r;
        i[r] = i[r] || function() {
            (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date();
        a = s.createElement(o),
            m = s.getElementsByTagName(o)[0];
        a.async = 1;
        a.src = g;
        m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');

    ga('create', 'UA-37896540-1', 'auto');
    ga('send', 'pageview');

</script>
<script type="text/javascript">var switchTo5x = true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({ publisher: "2fab054b-6cc5-4a49-9806-2e84a0babb25", doNotHash: false, doNotCopy: false, hashAddressBar: false });</script>

</body>
</html>

DF.Web/Views/Shared/_Top.cshtml
<a href="#" class="label label-warning pull-right"><i class="fa fa-angle-double-up"></i>&nbsp;&nbsp;Go to Top</a>

DF.Web/Views/Shared/_TopAd.cshtml
<div class="top-ad">
    <div class="row">
        <div class="col-md-8 top-ad-bkg">
        </div>
        <div class="col-md-4 top-ad-content text-center">
            <h2>Card holders stay free at The Beach</h2><br/>
            <button class="btn btn-success">More information</button>
        </div>
    </div>
</div>

DF.Web/Views/Shared/_VendorShortProfile.cshtml
<div class="vendor-short-profile">
    <div class="vendor-short-background">
        Pizzahut
    </div>
    <div class="vendor-short-desc">
        <div class="row">
            <a href="/vendor/pizzahut">
                <div class="col-sm-4">
                    DEALS<br/>
                    <span class="vendor-count">2300</span>
                </div>
                <div class="col-sm-4">
                    FOLLOWERS<br/>
                    <span class="vendor-count">12,000</span>
                </div>
                <div class="col-sm-4"></div>
            </a>
        </div>
        <br/>
        <button class="btn btn-info">
            <i class="btr bt-plus icon"></i>Follow
        </button>&nbsp;&nbsp;&nbsp;<span class="green"><i class="fa fa-check icon"></i>Verfied Account</span>
    </div>
</div>